# This config file is Bash shell syntax, and is included in all packaging scripts.

echo "Packaging configuration loaded."

# List of all Firebase products to include in the binary SDK package.
readonly -a product_list=(analytics app
)
